{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "movie-cast.fullname" . }}-nginx-config
  labels:
    {{- include "movie-cast.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
data:
  default.conf: |
    server {
      listen 8081;

      location /api/v1/movies/ {
        proxy_pass http://{{ include "movie-cast.fullname" . }}-movie-service:{{ .Values.movieService.service.port }}/api/v1/movies/;
      }

      location /api/v1/casts/ {
        proxy_pass http://{{ include "movie-cast.fullname" . }}-cast-service:{{ .Values.castService.service.port }}/api/v1/casts/;
      }
    }
{{- end }} 