{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "movie-cast.fullname" . }}-nginx
  labels:
    {{- include "movie-cast.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
      protocol: TCP
      name: http
      {{- if eq .Values.nginx.service.type "NodePort" }}
      nodePort: {{ .Values.nginx.service.nodePort }}
      {{- end }}
  selector:
    {{- include "movie-cast.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
{{- end }} 