apiVersion: v1
kind: Secret
metadata:
  name: movie-db-secret
type: Opaque
data:
  POSTGRES_USER: bW92aWVfZGJfdXNlcm5hbWU=  # movie_db_username en base64
  POSTGRES_PASSWORD: bW92aWVfZGJfcGFzc3dvcmQ=  # movie_db_password en base64
  POSTGRES_DB: bW92aWVfZGJfZGV2  # movie_db_dev en base64
---
apiVersion: v1
kind: Secret
metadata:
  name: cast-db-secret
type: Opaque
data:
  POSTGRES_USER: Y2FzdF9kYl91c2VybmFtZQ==  # cast_db_username en base64
  POSTGRES_PASSWORD: Y2FzdF9kYl9wYXNzd29yZA==  # cast_db_password en base64
  POSTGRES_DB: Y2FzdF9kYl9kZXY=  # cast_db_dev en base64 