# Development environment values
movieService:
  replicaCount: 1
  image:
    repository: killuazoaldyek/movie-service
    tag: latest
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  env:
    - name: DATABASE_URI
      value: postgresql://movie_db_username:movie_db_password@movie-cast-movie-db/movie_db_dev
    - name: CAST_SERVICE_HOST_URL
      value: http://movie-cast-cast-service:8000/api/v1/casts/

castService:
  replicaCount: 1
  image:
    repository: killuazoaldyek/cast-service
    tag: latest
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  env:
    - name: DATABASE_URI
      value: postgresql://cast_db_username:cast_db_password@movie-cast-cast-db/cast_db_dev

movieDb:
  enabled: true
  image:
    repository: postgres
    tag: 12.1-alpine
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    size: 1Gi
  env:
    - name: POSTGRES_USER
      value: movie_db_username
    - name: POSTGRES_PASSWORD
      value: movie_db_password
    - name: POSTGRES_DB
      value: movie_db_dev

castDb:
  enabled: true
  image:
    repository: postgres
    tag: 12.1-alpine
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    size: 1Gi
  env:
    - name: POSTGRES_USER
      value: cast_db_username
    - name: POSTGRES_PASSWORD
      value: cast_db_password
    - name: POSTGRES_DB
      value: cast_db_dev

nginx:
  enabled: true
  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 8081
    targetPort: 8081
  configMap:
    enabled: true
    name: nginx-config
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi

serviceAccount:
  create: true
  name: "movie-cast-sa" 